[features]
seeds = false
skip-lint = false
[programs.devnet]
fb_solana = "6Y6fezwG7zywo4srsARzVk172JZzgtC75QHYjYd9BFwq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/radud/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
